export const mockLiquidationData = [
  {
    id: 1,
    employee: "Juan Dela Cruz",
    department: "Finance",
    dateOfLiquidation: "2025-06-01",
    amountObtained: 10000,
    amountExpended: 9200,
    reimburseOrReturn: 800,
    transactions: [
      {
        date: "2025-05-28",
        rtNumber: "RT001",
        storeName: "National Bookstore",
        particulars: "Office supplies",
        from: "San Pedro",
        to: "Makati",
        transportation: "Grab",
        amount: 1200,
      },
      {
        date: "2025-05-29",
        rtNumber: "RT002",
        storeName: "SM Appliances",
        particulars: "Printer repair",
        from: "Muntinlupa",
        to: "Alabang",
        transportation: "Jeep",
        amount: 800,
      },
      {
        date: "2025-05-25",
        rtNumber: "RT003",
        storeName: "Mercury Drug",
        particulars: "First aid supplies",
        from: "Alabang",
        to: "Makati",
        transportation: "Taxi",
        amount: 2500,
      },
      {
        date: "2025-05-26",
        rtNumber: "RT004",
        storeName: "Watsons",
        particulars: "COVID kits",
        from: "Makati",
        to: "Taguig",
        transportation: "Bus",
        amount: 1100,
      },
      {
        date: "2025-06-02",
        rtNumber: "RT005",
        storeName: "Gasoline Station",
        particulars: "Fuel for delivery",
        from: "Santa Rosa",
        to: "Tagaytay",
        transportation: "Private car",
        amount: 3600,
      },
    ],
    proofImages: ["./receipt.jpg", "./receipt.jpg"],
  },

  {
    id: 2,
    employee: "Maria Santos",
    department: "HR",
    liquidationDate: "2025-06-03",
    obtained: 5000,
    expended: 4500,
    reimburseReturn: 500,
    transactions: [
      {
        date: "2025-05-25",
        rtNumber: "RT003",
        storeName: "Mercury Drug",
        particulars: "First aid supplies",
        from: "Alabang",
        to: "Makati",
        transportation: "Taxi",
        amount: 2500,
      },
      {
        date: "2025-05-26",
        rtNumber: "RT004",
        storeName: "Watsons",
        particulars: "COVID kits",
        from: "Makati",
        to: "Taguig",
        transportation: "Bus",
        amount: 2000,
      },
    ],
    proofImages: ["https://via.placeholder.com/300x200?text=Receipt+3"],
  },

  {
    id: 3,
    employee: "Roberto Cruz",
    department: "IT",
    liquidationDate: "2025-06-05",
    obtained: 7000,
    expended: 7000,
    reimburseReturn: 0,
    transactions: [
      {
        date: "2025-05-30",
        rtNumber: "RT005",
        storeName: "CD-R King",
        particulars: "Mouse and keyboard",
        from: "Pasig",
        to: "Ortigas",
        transportation: "Train",
        amount: 2000,
      },
      {
        date: "2025-05-31",
        rtNumber: "RT006",
        storeName: "Lazada",
        particulars: "External HDD",
        from: "Online",
        to: "Delivery",
        transportation: "Courier",
        amount: 5000,
      },
    ],
    proofImages: ["https://via.placeholder.com/300x200?text=Receipt+4"],
  },

  {
    id: 4,
    employee: "Angela Reyes",
    department: "Operations",
    liquidationDate: "2025-06-06",
    obtained: 8000,
    expended: 7600,
    reimburseReturn: 400,
    transactions: [
      {
        date: "2025-06-01",
        rtNumber: "RT007",
        storeName: "Office Warehouse",
        particulars: "Ink and paper",
        from: "San Pedro",
        to: "Santa Rosa",
        transportation: "Private car",
        amount: 4000,
      },
      {
        date: "2025-06-02",
        rtNumber: "RT008",
        storeName: "Gasoline Station",
        particulars: "Fuel for delivery",
        from: "Santa Rosa",
        to: "Tagaytay",
        transportation: "Private car",
        amount: 3600,
      },
    ],
    proofImages: [],
  },

  {
    id: 5,
    employee: "Leo Fernandez",
    department: "Marketing",
    liquidationDate: "2025-06-07",
    obtained: 6000,
    expended: 5000,
    reimburseReturn: 1000,
    transactions: [
      {
        date: "2025-06-03",
        rtNumber: "RT009",
        storeName: "Digital Print Hub",
        particulars: "Flyer printing",
        from: "Manila",
        to: "Quezon City",
        transportation: "LRT",
        amount: 3000,
      },
      {
        date: "2025-06-04",
        rtNumber: "RT010",
        storeName: "Globe Center",
        particulars: "SIM card & load",
        from: "QC",
        to: "Online",
        transportation: "Grab",
        amount: 2000,
      },
    ],
    proofImages: [
      "https://via.placeholder.com/300x200?text=Receipt+5",
      "https://via.placeholder.com/300x200?text=Receipt+6",
    ],
  },
];
