export const mockData = [
  {
    id: "crf-1",
    formType: "Cash Request",
    employee: "John Doe",
    position: "Research and Development",
    teamLead: "John Wick",
    department: "IT",
    description: "Laptop Purchase",
    expenseDate: "03/07/2025",
    category: "Equipment",
    paidBy: "Employee",
    total: "1350.85",
    status: "Pending",
    transactions: [
      { label: "Laptop", quantity: 1, price: 1200 },
      { label: "Mouse", quantity: 1, price: 50 },
      { label: "Keyboard", quantity: 1, price: 100.85 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-2",
    formType: "Cash Request",
    employee: "Michael Jackson",
    position: "IT Field Associate",
    department: "IT",
    description: "Training Expense",
    expenseDate: "03/10/2025",
    teamLead: "Jane Doe",
    category: "Education",
    paidBy: "Employee",
    total: "2400",
    status: "Pending",
    transactions: [
      { label: "Training Course", quantity: 4, price: 500 },
      { label: "Conference Ticket", quantity: 2, price: 200 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-3",
    formType: "Cash Request",
    employee: "Jane Smith",
    position: "IT Field Associate",
    department: "IT",
    description: "Training Expense",
    expenseDate: "03/10/2025",
    teamLead: "Jane Doe",
    category: "Education",
    paidBy: "Employee",
    total: "3300.00",
    status: "Approved",
    transactions: [
      { label: "Training Course", quantity: 2, price: 1500 },
      { label: "Conference Ticket", quantity: 1, price: 300 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-4",
    formType: "Cash Request",
    employee: "Mickey Mouse",
    position: "Finance",
    department: "Admin",
    description: "Food Expense",
    expenseDate: "03/01/2025",
    teamLead: "Jane Doe",
    category: "Meal Allowance",
    paidBy: "Employee",
    total: "5000.00",
    status: "Rejected",
    transactions: [
      { label: "Jollibee Mix and Match", quantity: 10, price: 500 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-5",
    formType: "Cash Request",
    employee: "Alice Cooper",
    position: "HR Manager",
    department: "Human Resources",
    description: "Office Supplies",
    expenseDate: "04/10/2025",
    teamLead: "Bob Marley",
    category: "Supplies",
    paidBy: "Employee",
    total: "550.00",
    status: "Approved",
    transactions: [
      { label: "Printer Paper", quantity: 10, price: 50 },
      { label: "Pens", quantity: 5, price: 10 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-6",
    formType: "Cash Request",
    employee: "Chris Hemsworth",
    position: "Software Engineer",
    department: "Development",
    description: "Software License",
    expenseDate: "04/12/2025",
    teamLead: "Scarlett Johansson",
    category: "Software",
    paidBy: "Employee",
    total: "2500.00",
    status: "Pending",
    transactions: [
      { label: "Visual Studio License", quantity: 1, price: 1000 },
      { label: "JetBrains License", quantity: 1, price: 1500 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-7",
    formType: "Cash Request",
    employee: "Tom Hiddleston",
    position: "DevOps Engineer",
    department: "Operations",
    description: "Server Hosting",
    expenseDate: "05/01/2025",
    teamLead: "Mark Ruffalo",
    category: "Hosting",
    paidBy: "Employee",
    total: "3500.00",
    status: "Approved",
    transactions: [
      { label: "AWS Hosting", quantity: 1, price: 2000 },
      { label: "Azure Hosting", quantity: 1, price: 1500 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-8",
    formType: "Cash Request",
    employee: "Emily Blunt",
    position: "Marketing Manager",
    department: "Marketing",
    description: "Advertising Campaign",
    expenseDate: "05/03/2025",
    teamLead: "John Cena",
    category: "Marketing",
    paidBy: "Employee",
    total: "5000.00",
    status: "Pending",
    transactions: [
      { label: "Google Ads", quantity: 1, price: 3000 },
      { label: "Facebook Ads", quantity: 1, price: 2000 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-9",
    formType: "Cash Request",
    employee: "Hugh Jackman",
    position: "Creative Director",
    department: "Design",
    description: "Graphics Design",
    expenseDate: "06/02/2025",
    teamLead: "Emma Stone",
    category: "Design",
    paidBy: "Employee",
    total: "2200.00",
    status: "Rejected",
    transactions: [
      { label: "Adobe Photoshop License", quantity: 1, price: 1200 },
      { label: "Illustrator Subscription", quantity: 1, price: 1000 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-10",
    formType: "Cash Request",
    employee: "Zoe Saldana",
    position: "Data Scientist",
    department: "Analytics",
    description: "Data Analysis Tools",
    expenseDate: "06/15/2025",
    teamLead: "Chris Pratt",
    category: "Software",
    paidBy: "Employee",
    total: "6000.00",
    status: "Approved",
    transactions: [
      { label: "RStudio License", quantity: 1, price: 1500 },
      { label: "Tableau License", quantity: 1, price: 4500 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-11",
    formType: "Cash Request",
    employee: "Daniel Craig",
    position: "Project Manager",
    department: "Management",
    description: "Project Supplies",
    expenseDate: "06/22/2025",
    teamLead: "Judi Dench",
    category: "Supplies",
    paidBy: "Employee",
    total: "650.00",
    status: "Pending",
    transactions: [
      { label: "Whiteboards", quantity: 3, price: 200 },
      { label: "Markers", quantity: 10, price: 5 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-12",
    formType: "Cash Request",
    employee: "Will Smith",
    position: "Sales Manager",
    department: "Sales",
    description: "Sales Incentives",
    expenseDate: "06/30/2025",
    teamLead: "Kevin Hart",
    category: "Incentives",
    paidBy: "Employee",
    total: "8000.00",
    status: "Rejected",
    transactions: [
      { label: "Team Incentive", quantity: 5, price: 1000 },
      { label: "Top Performer Bonus", quantity: 2, price: 1500 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-13",
    formType: "Cash Request",
    employee: "Morgan Freeman",
    position: "Customer Support Lead",
    department: "Support",
    description: "Customer Support Software",
    expenseDate: "07/02/2025",
    teamLead: "Samuel L. Jackson",
    category: "Software",
    paidBy: "Employee",
    total: "4500.00",
    status: "Approved",
    transactions: [
      { label: "Zendesk Subscription", quantity: 1, price: 2000 },
      { label: "Freshdesk Subscription", quantity: 1, price: 2500 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-14",
    formType: "Cash Request",
    employee: "Johnny Depp",
    position: "Legal Advisor",
    department: "Legal",
    description: "Legal Fees",
    expenseDate: "07/10/2025",
    teamLead: "Robert Downey Jr.",
    category: "Legal",
    paidBy: "Employee",
    total: "21000.00",
    status: "Pending",
    transactions: [
      { label: "Court Filing Fee", quantity: 1, price: 14000 },
      { label: "Consultation Fee", quantity: 2, price: 3500 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-15",
    formType: "Cash Request",
    employee: "Scarlett Johansson",
    position: "UI/UX Designer",
    department: "Design",
    description: "UX Research Tools",
    expenseDate: "07/15/2025",
    teamLead: "Chris Hemsworth",
    category: "Tools",
    paidBy: "Employee",
    total: "3500.00",
    status: "Approved",
    transactions: [
      { label: "UserTesting Subscription", quantity: 1, price: 1500 },
      { label: "Sketch License", quantity: 1, price: 2000 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-16",
    formType: "Cash Request",
    employee: "Kimi No Nawa",
    position: "Actor",
    department: "Entertainment",
    description: "Movie Expenses",
    expenseDate: "08/15/2025",
    teamLead: "Chris Hemsworth",
    category: "Entertainment",
    paidBy: "Employee",
    total: "15000.00",
    status: "Pending",
    transactions: [
      { label: "Costume Rental", quantity: 1, price: 2500 },
      { label: "Travel Expenses", quantity: 1, price: 5000 },
      { label: "Film Equipment", quantity: 1, price: 7500 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-17",
    formType: "Cash Request",
    employee: "Timothy Bradley",
    position: "Actor",
    department: "Entertainment",
    description: "Movie Expenses",
    expenseDate: "09/20/2025",
    teamLead: "Mark Ruffalo",
    category: "Entertainment",
    paidBy: "Employee",
    total: "10400",
    status: "Pending",
    transactions: [
      { label: "On-Set Catering", quantity: 3, price: 800 },
      { label: "Location Fees", quantity: 1, price: 4000 },
      { label: "Set Design", quantity: 2, price: 2000 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-18",
    formType: "Cash Request",
    employee: "Chris Pratt",
    position: "Actor",
    department: "Entertainment",
    description: "Movie Expenses",
    expenseDate: "09/30/2025",
    teamLead: "Scarlett Johansson",
    category: "Entertainment",
    paidBy: "Employee",
    total: "12000.00",
    status: "Pending",
    transactions: [
      { label: "Travel Expenses", quantity: 1, price: 3000 },
      { label: "Costume Rentals", quantity: 2, price: 1000 },
      { label: "Set Equipment", quantity: 1, price: 7000 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-19",
    formType: "Cash Request",
    employee: "Natalie Portman",
    position: "Data Analyst",
    department: "Analytics",
    description: "Data Analysis Tools",
    expenseDate: "09/30/2025",
    teamLead: "Chris Pratt",
    category: "Software",
    paidBy: "Employee",
    total: "4500.00",
    status: "Pending",
    transactions: [
      { label: "Power BI License", quantity: 1, price: 1500 },
      { label: "SQL Server License", quantity: 1, price: 3000 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-20",
    formType: "Cash Request",
    employee: "Mark Ruffalo",
    position: "Project Manager",
    department: "Management",
    description: "Team Building",
    expenseDate: "10/01/2025",
    teamLead: "Robert Downey Jr.",
    category: "Incentives",
    paidBy: "Employee",
    total: "3000.00",
    status: "Pending",
    transactions: [
      { label: "Team Dinner", quantity: 1, price: 1500 },
      { label: "Outdoor Activities", quantity: 1, price: 1500 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-21",
    formType: "Cash Request",
    employee: "Tom Bradley",
    position: "DevOps Engineer",
    department: "Operations",
    description: "Server Maintenance",
    expenseDate: "10/05/2025",
    teamLead: "Mark Ruffalo",
    category: "Hosting",
    paidBy: "Employee",
    total: "12000.00",
    status: "Pending",
    transactions: [
      { label: "Server Maintenance", quantity: 1, price: 8000 },
      { label: "Server Upgrades", quantity: 1, price: 4000 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-22",
    formType: "Cash Request",
    employee: "Emma Stone",
    position: "Creative Director",
    department: "Design",
    description: "Graphic Design Software",
    expenseDate: "10/15/2025",
    teamLead: "Hugh Jackman",
    category: "Design",
    paidBy: "Employee",
    total: "3500.00",
    status: "Pending",
    transactions: [
      { label: "Adobe Illustrator Subscription", quantity: 1, price: 1500 },
      { label: "CorelDraw License", quantity: 1, price: 2000 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-23",
    formType: "Cash Request",
    employee: "Florence Pugh",
    position: "UI/UX Designer",
    department: "Product Design",
    description: "Design Sprint Workshop",
    expenseDate: "10/25/2025",
    teamLead: "Emily Blunt",
    category: "Training",
    paidBy: "Employee",
    total: "3200.00",
    status: "Pending",
    transactions: [
      { label: "Workshop Fee", quantity: 1, price: 3000 },
      { label: "Materials", quantity: 1, price: 200 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-24",
    formType: "Cash Request",
    employee: "Joseph Quinn",
    position: "Network Engineer",
    department: "IT",
    description: "Router Replacement",
    expenseDate: "10/27/2025",
    teamLead: "Gaten Matarazzo",
    category: "Hardware",
    paidBy: "Employee",
    total: "4500.00",
    status: "Approved",
    transactions: [{ label: "Enterprise Router", quantity: 1, price: 4500 }],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-25",
    formType: "Cash Request",
    employee: "Pedro Pascal",
    position: "Security Consultant",
    department: "Security",
    description: "Cybersecurity Audit",
    expenseDate: "10/30/2025",
    teamLead: "Bella Ramsey",
    category: "Consulting",
    paidBy: "Employee",
    total: "7500.00",
    status: "Pending",
    transactions: [{ label: "Audit Services", quantity: 1, price: 7500 }],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "crf-26",
    formType: "Cash Request",
    employee: "Anya Taylor-Joy",
    position: "Business Analyst",
    department: "Business Intelligence",
    description: "Market Research Tools",
    expenseDate: "10/31/2025",
    teamLead: "Thomas Brodie-Sangster",
    category: "Software",
    paidBy: "Employee",
    total: "5800.00",
    status: "Approved",
    transactions: [
      { label: "Survey Platform Subscription", quantity: 1, price: 5800 },
    ],
    images: [
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
      "/receipt.jpg",
    ],
  },
  {
    id: "liq-1",
    formType: "Liquidation",
    description: "sample data",
    employee: "Juan Dela Cruz",
    department: "Finance",
    dateOfLiquidation: "2025-06-01",
    status: "Pending",
    amountObtained: 10000,
    amountExpended: 9200,
    reimburseOrReturn: 800,
    transactions: [
      {
        date: "2025-05-28",
        rtNumber: "RT001",
        storeName: "National Bookstore",
        particulars: "Office supplies",
        from: "San Pedro",
        to: "Makati",
        transportation: "Grab",
        amount: 1200,
      },
      {
        date: "2025-05-29",
        rtNumber: "RT002",
        storeName: "SM Appliances",
        particulars: "Printer repair",
        from: "Muntinlupa",
        to: "Alabang",
        transportation: "Jeep",
        amount: 800,
      },
      {
        date: "2025-05-25",
        rtNumber: "RT003",
        storeName: "Mercury Drug",
        particulars: "First aid supplies",
        from: "Alabang",
        to: "Makati",
        transportation: "Taxi",
        amount: 2500,
      },
      {
        date: "2025-05-26",
        rtNumber: "RT004",
        storeName: "Watsons",
        particulars: "COVID kits",
        from: "Makati",
        to: "Taguig",
        transportation: "Bus",
        amount: 1100,
      },
      {
        date: "2025-06-02",
        rtNumber: "RT005",
        storeName: "Gasoline Station",
        particulars: "Fuel for delivery",
        from: "Santa Rosa",
        to: "Tagaytay",
        transportation: "Private car",
        amount: 3600,
      },
    ],
    proofImages: ["./receipt.jpg", "./receipt.jpg"],
  },
  {
    id: "liq-2",
    formType: "Liquidation",
    description: "sample data",
    employee: "Maria Santos",
    department: "HR",
    dateOfLiquidation: "2025-06-03",
    status: "Pending",
    amountObtained: 5000,
    amountExpended: 4500,
    reimburseOrReturn: 500,
    transactions: [
      {
        date: "2025-05-25",
        rtNumber: "RT003",
        storeName: "Mercury Drug",
        particulars: "First aid supplies",
        from: "Alabang",
        to: "Makati",
        transportation: "Taxi",
        amount: 2500,
      },
      {
        date: "2025-05-26",
        rtNumber: "RT004",
        storeName: "Watsons",
        particulars: "COVID kits",
        from: "Makati",
        to: "Taguig",
        transportation: "Bus",
        amount: 2000,
      },
    ],
    proofImages: ["./receipt.jpg", "./receipt.jpg"],
  },
  {
    id: "liq-3",
    formType: "Liquidation",
    description: "sample data",
    employee: "Roberto Cruz",
    department: "IT",
    dateOfLiquidation: "2025-06-05",
    status: "Pending",
    amountObtained: 7000,
    amountExpended: 7000,
    reimburseOrReturn: 0,
    transactions: [
      {
        date: "2025-05-30",
        rtNumber: "RT005",
        storeName: "CD-R King",
        particulars: "Mouse and keyboard",
        from: "Pasig",
        to: "Ortigas",
        transportation: "Train",
        amount: 2000,
      },
      {
        date: "2025-05-31",
        rtNumber: "RT006",
        storeName: "Lazada",
        particulars: "External HDD",
        from: "Online",
        to: "Delivery",
        transportation: "Courier",
        amount: 5000,
      },
    ],
    proofImages: ["./receipt.jpg", "./receipt.jpg"],
  },
  {
    id: "liq-4",
    formType: "Liquidation",
    description: "sample data",
    employee: "Angela Reyes",
    department: "Operations",
    dateOfLiquidation: "2025-06-06",
    status: "Pending",
    amountObtained: 8000,
    amountExpended: 7600,
    reimburseOrReturn: 400,
    transactions: [
      {
        date: "2025-06-01",
        rtNumber: "RT007",
        storeName: "Office Warehouse",
        particulars: "Ink and paper",
        from: "San Pedro",
        to: "Santa Rosa",
        transportation: "Private car",
        amount: 4000,
      },
      {
        date: "2025-06-02",
        rtNumber: "RT008",
        storeName: "Gasoline Station",
        particulars: "Fuel for delivery",
        from: "Santa Rosa",
        to: "Tagaytay",
        transportation: "Private car",
        amount: 3600,
      },
    ],
    proofImages: ["./receipt.jpg", "./receipt.jpg"],
  },
  {
    id: "liq-5",
    formType: "Liquidation",
    description: "sample data",
    employee: "Leo Fernandez",
    department: "Marketing",
    dateOfLiquidation: "2025-06-07",
    status: "Pending",
    amountObtained: 6000,
    amountExpended: 5000,
    reimburseOrReturn: 1000,
    transactions: [
      {
        date: "2025-06-03",
        rtNumber: "RT009",
        storeName: "Digital Print Hub",
        particulars: "Flyer printing",
        from: "Manila",
        to: "Quezon City",
        transportation: "LRT",
        amount: 3000,
      },
      {
        date: "2025-06-04",
        rtNumber: "RT010",
        storeName: "Globe Center",
        particulars: "SIM card & load",
        from: "QC",
        to: "Online",
        transportation: "Grab",
        amount: 2000,
      },
    ],
    proofImages: ["./receipt.jpg", "./receipt.jpg"],
  },
];
