export const mockData = [
  // {
  //   id: 1,
  //   employee: "John Doe",
  //   position: "Research and Development",
  //   teamLead: "John Wick",
  //   department: "IT",
  //   description: "Laptop Purchase",
  //   expenseDate: "03/07/2025",
  //   category: "Equipment",
  //   paidBy: "Employee",
  //   total: "1350.85",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Laptop", quantity: 1, price: 1200 },
  //     { label: "Mouse", quantity: 1, price: 50 },
  //     { label: "Keyboard", quantity: 1, price: 100.85 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 2,
  //   employee: "Michael Jackson",
  //   position: "IT Field Associate",
  //   department: "IT",
  //   description: "Training Expense",
  //   expenseDate: "03/10/2025",
  //   teamLead: "Jane Doe",
  //   category: "Education",
  //   paidBy: "Employee",
  //   total: "2400",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Training Course", quantity: 4, price: 500 },
  //     { label: "Conference Ticket", quantity: 2, price: 200 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 3,
  //   employee: "Jane Smith",
  //   position: "IT Field Associate",
  //   department: "IT",
  //   description: "Training Expense",
  //   expenseDate: "03/10/2025",
  //   teamLead: "Jane Doe",
  //   category: "Education",
  //   paidBy: "Employee",
  //   total: "3300.00",
  //   status: "Approved",
  //   transactions: [
  //     { label: "Training Course", quantity: 2, price: 1500 },
  //     { label: "Conference Ticket", quantity: 1, price: 300 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 4,
  //   employee: "Mickey Mouse",
  //   position: "Finance",
  //   department: "Admin",
  //   description: "Food Expense",
  //   expenseDate: "03/01/2025",
  //   teamLead: "Jane Doe",
  //   category: "Meal Allowance",
  //   paidBy: "Employee",
  //   total: "5000.00",
  //   status: "Rejected",
  //   transactions: [
  //     { label: "Jollibee Mix and Match", quantity: 10, price: 500 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 5,
  //   employee: "Alice Cooper",
  //   position: "HR Manager",
  //   department: "Human Resources",
  //   description: "Office Supplies",
  //   expenseDate: "04/10/2025",
  //   teamLead: "Bob Marley",
  //   category: "Supplies",
  //   paidBy: "Employee",
  //   total: "550.00",
  //   status: "Approved",
  //   transactions: [
  //     { label: "Printer Paper", quantity: 10, price: 50 },
  //     { label: "Pens", quantity: 5, price: 10 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 6,
  //   employee: "Chris Hemsworth",
  //   position: "Software Engineer",
  //   department: "Development",
  //   description: "Software License",
  //   expenseDate: "04/12/2025",
  //   teamLead: "Scarlett Johansson",
  //   category: "Software",
  //   paidBy: "Employee",
  //   total: "2500.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Visual Studio License", quantity: 1, price: 1000 },
  //     { label: "JetBrains License", quantity: 1, price: 1500 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 7,
  //   employee: "Tom Hiddleston",
  //   position: "DevOps Engineer",
  //   department: "Operations",
  //   description: "Server Hosting",
  //   expenseDate: "05/01/2025",
  //   teamLead: "Mark Ruffalo",
  //   category: "Hosting",
  //   paidBy: "Employee",
  //   total: "3500.00",
  //   status: "Approved",
  //   transactions: [
  //     { label: "AWS Hosting", quantity: 1, price: 2000 },
  //     { label: "Azure Hosting", quantity: 1, price: 1500 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 8,
  //   employee: "Emily Blunt",
  //   position: "Marketing Manager",
  //   department: "Marketing",
  //   description: "Advertising Campaign",
  //   expenseDate: "05/03/2025",
  //   teamLead: "John Cena",
  //   category: "Marketing",
  //   paidBy: "Employee",
  //   total: "5000.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Google Ads", quantity: 1, price: 3000 },
  //     { label: "Facebook Ads", quantity: 1, price: 2000 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 9,
  //   employee: "Hugh Jackman",
  //   position: "Creative Director",
  //   department: "Design",
  //   description: "Graphics Design",
  //   expenseDate: "06/02/2025",
  //   teamLead: "Emma Stone",
  //   category: "Design",
  //   paidBy: "Employee",
  //   total: "2200.00",
  //   status: "Rejected",
  //   transactions: [
  //     { label: "Adobe Photoshop License", quantity: 1, price: 1200 },
  //     { label: "Illustrator Subscription", quantity: 1, price: 1000 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 10,
  //   employee: "Zoe Saldana",
  //   position: "Data Scientist",
  //   department: "Analytics",
  //   description: "Data Analysis Tools",
  //   expenseDate: "06/15/2025",
  //   teamLead: "Chris Pratt",
  //   category: "Software",
  //   paidBy: "Employee",
  //   total: "6000.00",
  //   status: "Approved",
  //   transactions: [
  //     { label: "RStudio License", quantity: 1, price: 1500 },
  //     { label: "Tableau License", quantity: 1, price: 4500 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 11,
  //   employee: "Daniel Craig",
  //   position: "Project Manager",
  //   department: "Management",
  //   description: "Project Supplies",
  //   expenseDate: "06/22/2025",
  //   teamLead: "Judi Dench",
  //   category: "Supplies",
  //   paidBy: "Employee",
  //   total: "650.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Whiteboards", quantity: 3, price: 200 },
  //     { label: "Markers", quantity: 10, price: 5 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 12,
  //   employee: "Will Smith",
  //   position: "Sales Manager",
  //   department: "Sales",
  //   description: "Sales Incentives",
  //   expenseDate: "06/30/2025",
  //   teamLead: "Kevin Hart",
  //   category: "Incentives",
  //   paidBy: "Employee",
  //   total: "8000.00",
  //   status: "Rejected",
  //   transactions: [
  //     { label: "Team Incentive", quantity: 5, price: 1000 },
  //     { label: "Top Performer Bonus", quantity: 2, price: 1500 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 13,
  //   employee: "Morgan Freeman",
  //   position: "Customer Support Lead",
  //   department: "Support",
  //   description: "Customer Support Software",
  //   expenseDate: "07/02/2025",
  //   teamLead: "Samuel L. Jackson",
  //   category: "Software",
  //   paidBy: "Employee",
  //   total: "4500.00",
  //   status: "Approved",
  //   transactions: [
  //     { label: "Zendesk Subscription", quantity: 1, price: 2000 },
  //     { label: "Freshdesk Subscription", quantity: 1, price: 2500 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 14,
  //   employee: "Johnny Depp",
  //   position: "Legal Advisor",
  //   department: "Legal",
  //   description: "Legal Fees",
  //   expenseDate: "07/10/2025",
  //   teamLead: "Robert Downey Jr.",
  //   category: "Legal",
  //   paidBy: "Employee",
  //   total: "21000.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Court Filing Fee", quantity: 1, price: 14000 },
  //     { label: "Consultation Fee", quantity: 2, price: 3500 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 15,
  //   employee: "Scarlett Johansson",
  //   position: "UI/UX Designer",
  //   department: "Design",
  //   description: "UX Research Tools",
  //   expenseDate: "07/15/2025",
  //   teamLead: "Chris Hemsworth",
  //   category: "Tools",
  //   paidBy: "Employee",
  //   total: "3500.00",
  //   status: "Approved",
  //   transactions: [
  //     { label: "UserTesting Subscription", quantity: 1, price: 1500 },
  //     { label: "Sketch License", quantity: 1, price: 2000 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 16,
  //   employee: "Kimi No Nawa",
  //   position: "Actor",
  //   department: "Entertainment",
  //   description: "Movie Expenses",
  //   expenseDate: "08/15/2025",
  //   teamLead: "Chris Hemsworth",
  //   category: "Entertainment",
  //   paidBy: "Employee",
  //   total: "15000.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Costume Rental", quantity: 1, price: 2500 },
  //     { label: "Travel Expenses", quantity: 1, price: 5000 },
  //     { label: "Film Equipment", quantity: 1, price: 7500 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 17,
  //   employee: "Timothy Bradley",
  //   position: "Actor",
  //   department: "Entertainment",
  //   description: "Movie Expenses",
  //   expenseDate: "09/20/2025",
  //   teamLead: "Mark Ruffalo",
  //   category: "Entertainment",
  //   paidBy: "Employee",
  //   total: "10400",
  //   status: "Pending",
  //   transactions: [
  //     { label: "On-Set Catering", quantity: 3, price: 800 },
  //     { label: "Location Fees", quantity: 1, price: 4000 },
  //     { label: "Set Design", quantity: 2, price: 2000 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 18,
  //   employee: "Chris Pratt",
  //   position: "Actor",
  //   department: "Entertainment",
  //   description: "Movie Expenses",
  //   expenseDate: "09/30/2025",
  //   teamLead: "Scarlett Johansson",
  //   category: "Entertainment",
  //   paidBy: "Employee",
  //   total: "12000.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Travel Expenses", quantity: 1, price: 3000 },
  //     { label: "Costume Rentals", quantity: 2, price: 1000 },
  //     { label: "Set Equipment", quantity: 1, price: 7000 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 19,
  //   employee: "Chris Evans",
  //   position: "Frontend Developer",
  //   department: "Development",
  //   description: "Website Redesign",
  //   expenseDate: "09/25/2025",
  //   teamLead: "Scarlett Johansson",
  //   category: "Design",
  //   paidBy: "Employee",
  //   total: "8000.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "UI/UX Redesign", quantity: 1, price: 4000 },
  //     { label: "New Website Hosting", quantity: 1, price: 4000 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 20,
  //   employee: "Natalie Portman",
  //   position: "Data Analyst",
  //   department: "Analytics",
  //   description: "Data Analysis Tools",
  //   expenseDate: "09/30/2025",
  //   teamLead: "Chris Pratt",
  //   category: "Software",
  //   paidBy: "Employee",
  //   total: "4500.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Power BI License", quantity: 1, price: 1500 },
  //     { label: "SQL Server License", quantity: 1, price: 3000 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 21,
  //   employee: "Mark Ruffalo",
  //   position: "Project Manager",
  //   department: "Management",
  //   description: "Team Building",
  //   expenseDate: "10/01/2025",
  //   teamLead: "Robert Downey Jr.",
  //   category: "Incentives",
  //   paidBy: "Employee",
  //   total: "3000.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Team Dinner", quantity: 1, price: 1500 },
  //     { label: "Outdoor Activities", quantity: 1, price: 1500 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 22,
  //   employee: "Tom Bradley",
  //   position: "DevOps Engineer",
  //   department: "Operations",
  //   description: "Server Maintenance",
  //   expenseDate: "10/05/2025",
  //   teamLead: "Mark Ruffalo",
  //   category: "Hosting",
  //   paidBy: "Employee",
  //   total: "12000.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Server Maintenance", quantity: 1, price: 8000 },
  //     { label: "Server Upgrades", quantity: 1, price: 4000 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 23,
  //   employee: "Jennifer Lawrence",
  //   position: "Marketing Specialist",
  //   department: "Marketing",
  //   description: "Product Launch Campaign",
  //   expenseDate: "10/10/2025",
  //   teamLead: "John Cena",
  //   category: "Marketing",
  //   paidBy: "Employee",
  //   total: "7000.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Social Media Ads", quantity: 1, price: 3000 },
  //     { label: "Influencer Collaboration", quantity: 1, price: 4000 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 24,
  //   employee: "Emma Stone",
  //   position: "Creative Director",
  //   department: "Design",
  //   description: "Graphic Design Software",
  //   expenseDate: "10/15/2025",
  //   teamLead: "Hugh Jackman",
  //   category: "Design",
  //   paidBy: "Employee",
  //   total: "3500.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Adobe Illustrator Subscription", quantity: 1, price: 1500 },
  //     { label: "CorelDraw License", quantity: 1, price: 2000 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 25,
  //   employee: "Vin Diesel",
  //   position: "Software Engineer",
  //   department: "Development",
  //   description: "New Software Tools",
  //   expenseDate: "10/20/2025",
  //   teamLead: "Chris Hemsworth",
  //   category: "Software",
  //   paidBy: "Employee",
  //   total: "6000.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "JetBrains Tools", quantity: 1, price: 3000 },
  //     { label: "Visual Studio Tools", quantity: 1, price: 3000 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 26,
  //   employee: "Florence Pugh",
  //   position: "UI/UX Designer",
  //   department: "Product Design",
  //   description: "Design Sprint Workshop",
  //   expenseDate: "10/25/2025",
  //   teamLead: "Emily Blunt",
  //   category: "Training",
  //   paidBy: "Employee",
  //   total: "3200.00",
  //   status: "Pending",
  //   transactions: [
  //     { label: "Workshop Fee", quantity: 1, price: 3000 },
  //     { label: "Materials", quantity: 1, price: 200 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 27,
  //   employee: "Joseph Quinn",
  //   position: "Network Engineer",
  //   department: "IT",
  //   description: "Router Replacement",
  //   expenseDate: "10/27/2025",
  //   teamLead: "Gaten Matarazzo",
  //   category: "Hardware",
  //   paidBy: "Employee",
  //   total: "4500.00",
  //   status: "Approved",
  //   transactions: [{ label: "Enterprise Router", quantity: 1, price: 4500 }],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 28,
  //   employee: "Sadie Sink",
  //   position: "Social Media Manager",
  //   department: "Marketing",
  //   description: "Influencer Collaboration",
  //   expenseDate: "10/29/2025",
  //   teamLead: "Millie Bobby Brown",
  //   category: "Advertising",
  //   paidBy: "Employee",
  //   total: "6000.00",
  //   status: "Pending",
  //   transactions: [{ label: "Influencer Fee", quantity: 1, price: 6000 }],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 29,
  //   employee: "Pedro Pascal",
  //   position: "Security Consultant",
  //   department: "Security",
  //   description: "Cybersecurity Audit",
  //   expenseDate: "10/30/2025",
  //   teamLead: "Bella Ramsey",
  //   category: "Consulting",
  //   paidBy: "Employee",
  //   total: "7500.00",
  //   status: "Pending",
  //   transactions: [{ label: "Audit Services", quantity: 1, price: 7500 }],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
  // {
  //   id: 30,
  //   employee: "Anya Taylor-Joy",
  //   position: "Business Analyst",
  //   department: "Business Intelligence",
  //   description: "Market Research Tools",
  //   expenseDate: "10/31/2025",
  //   teamLead: "Thomas Brodie-Sangster",
  //   category: "Software",
  //   paidBy: "Employee",
  //   total: "5800.00",
  //   status: "Approved",
  //   transactions: [
  //     { label: "Survey Platform Subscription", quantity: 1, price: 5800 },
  //   ],
  //   images: [
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //     "/receipt.jpg",
  //   ],
  // },
];
