export const revolvingFundColumns = [
  { label: "ID", accessor: "id" },
  { label: "Budget Name", accessor: "budgetName" },
  { label: "Start Date", accessor: "startDate" },
  { label: "End Date", accessor: "endDate" },
  { label: "Beginning", accessor: "beginning" },
  { label: "Added", accessor: "added" },
  { label: "Total Fund", accessor: "totalFund" },
  { label: "Issued", accessor: "issued" },
  { label: "Returned", accessor: "returned" },
  { label: "Outstanding", accessor: "outstanding" },
  { label: "Amount Expended", accessor: "amountExpended" },
  { label: "Ended", accessor: "ended" },
  { label: "Liquidated", accessor: "liquidated" },
  { label: "Unliquidated", accessor: "unliquidated" },
  { label: "Balance", accessor: "balance" },
  { label: "Status", accessor: "status" },
  { label: "Actions", accessor: "actions" },
];

export const cashDisbursementColumns = [
  { label: "ID", accessor: "id" },
  { label: "Revolving Fund", accessor: "revolvingFund" },
  { label: "Date Issue", accessor: "dateIssue" },
  { label: "Received By", accessor: "receivedBy" },
  { label: "Department", accessor: "department" },
  { label: "Particulars", accessor: "particulars" },
  { label: "Cash Voucher", accessor: "cashVoucher" },
  { label: "Amount Issue", accessor: "amountIssue" },
  { label: "Amount Return", accessor: "amountReturn" },
  { label: "Amount Expended", accessor: "amountExpended" },
  { label: "Outstanding Amount", accessor: "outstandingAmount" },
  { label: "Status", accessor: "status" },
  { label: "Date Liquidated", accessor: "dateLiquidated" },
  { label: "Actions", accessor: "actions" },
];
