export const mockBudgets = [
  {
    id: 1,
    department: "IT Department",
    allocated: 100000,
    used: 45000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-001",
        description: "Monthly internet allowance",
        amount: 10000,
        status: "Approved",
        date: "2025-01-10",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-002",
        description: "Equipment purchase",
        amount: 15000,
        status: "Pending",
        date: "2025-02-05",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-003",
        description: "Travel expenses",
        amount: 20000,
        status: "Approved",
        date: "2025-03-12",
        month: "Mar",
      },
      {
        type: "Cash Request",
        referenceId: "CR-0026",
        description: "Monthly internet allowance",
        amount: 10000,
        status: "Approved",
        date: "2025-01-10",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-0072",
        description: "Equipment purchase",
        amount: 15000,
        status: "Pending",
        date: "2025-02-05",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-0083",
        description: "Travel expenses",
        amount: 20000,
        status: "Rejected",
        date: "2025-03-12",
        month: "Mar",
      },
    ],
  },
  {
    id: 2,
    department: "HR Department",
    allocated: 75000,
    used: 25000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-004",
        description: "Training materials",
        amount: 5000,
        status: "Approved",
        date: "2025-01-08",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-005",
        description: "Onboarding kits",
        amount: 10000,
        status: "Approved",
        date: "2025-02-15",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-006",
        description: "Recruitment meal expenses",
        amount: 10000,
        status: "Rejected",
        date: "2025-03-09",
        month: "Mar",
      },
    ],
  },
  {
    id: 3,
    department: "Finance Department",
    allocated: 120000,
    used: 95000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-007",
        description: "Petty cash fund",
        amount: 20000,
        status: "Approved",
        date: "2025-01-03",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-008",
        description: "Software subscription",
        amount: 40000,
        status: "Approved",
        date: "2025-02-20",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-009",
        description: "Client meeting refreshments",
        amount: 35000,
        status: "Pending",
        date: "2025-03-14",
        month: "Mar",
      },
    ],
  },
  {
    id: 4,
    department: "Logistics Department",
    allocated: 50000,
    used: 20000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-010",
        description: "Fuel for deliveries",
        amount: 5000,
        status: "Approved",
        date: "2025-01-05",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-011",
        description: "Packaging supplies",
        amount: 7000,
        status: "Pending",
        date: "2025-02-11",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-012",
        description: "Out-of-town delivery expenses",
        amount: 8000,
        status: "Approved",
        date: "2025-03-18",
        month: "Mar",
      },
    ],
  },
  {
    id: 5,
    department: "Admin Department",
    allocated: 100000,
    used: 45000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-013",
        description: "Office supplies",
        amount: 10000,
        status: "Approved",
        date: "2025-01-02",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-014",
        description: "Coffee and pantry restock",
        amount: 15000,
        status: "Approved",
        date: "2025-02-09",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-015",
        description: "Parking reimbursements",
        amount: 20000,
        status: "Pending",
        date: "2025-03-20",
        month: "Mar",
      },
    ],
  },
  {
    id: 6,
    department: "Marketing Department",
    allocated: 75000,
    used: 25000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-016",
        description: "Ad campaign boost",
        amount: 8000,
        status: "Approved",
        date: "2025-01-14",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-017",
        description: "Social media tools",
        amount: 9000,
        status: "Approved",
        date: "2025-02-13",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-018",
        description: "Event hosting reimbursement",
        amount: 8000,
        status: "Rejected",
        date: "2025-03-16",
        month: "Mar",
      },
    ],
  },
  {
    id: 7,
    department: "Operations",
    allocated: 50000,
    used: 40000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-019",
        description: "Site inspection funds",
        amount: 10000,
        status: "Approved",
        date: "2025-01-07",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-020",
        description: "Tools and equipment",
        amount: 15000,
        status: "Pending",
        date: "2025-02-17",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-021",
        description: "Emergency repairs",
        amount: 15000,
        status: "Approved",
        date: "2025-03-22",
        month: "Mar",
      },
    ],
  },
  {
    id: 8,
    department: "Engineering Department",
    allocated: 80000,
    used: 55000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-022",
        description: "Project materials",
        amount: 15000,
        status: "Approved",
        date: "2025-01-11",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-023",
        description: "Contractor payment",
        amount: 20000,
        status: "Pending",
        date: "2025-02-14",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-024",
        description: "Engineering licenses",
        amount: 20000,
        status: "Approved",
        date: "2025-03-11",
        month: "Mar",
      },
    ],
  },
  {
    id: 9,
    department: "Sales Department",
    allocated: 90000,
    used: 60000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-025",
        description: "Client meeting funds",
        amount: 20000,
        status: "Approved",
        date: "2025-01-06",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-026",
        description: "Sales event materials",
        amount: 15000,
        status: "Pending",
        date: "2025-02-18",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-027",
        description: "Travel expenses",
        amount: 25000,
        status: "Approved",
        date: "2025-03-15",
        month: "Mar",
      },
    ],
  },
  {
    id: 10,
    department: "Procurement Department",
    allocated: 95000,
    used: 70000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-028",
        description: "Inventory restock",
        amount: 25000,
        status: "Approved",
        date: "2025-01-09",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-029",
        description: "Supplier payment",
        amount: 20000,
        status: "Approved",
        date: "2025-02-10",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-030",
        description: "Courier service fees",
        amount: 25000,
        status: "Pending",
        date: "2025-03-13",
        month: "Mar",
      },
    ],
  },
  {
    id: 11,
    department: "Legal Department",
    allocated: 60000,
    used: 35000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-031",
        description: "Legal research materials",
        amount: 10000,
        status: "Approved",
        date: "2025-01-12",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-032",
        description: "Contract review tools",
        amount: 10000,
        status: "Pending",
        date: "2025-02-21",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-033",
        description: "Bar membership fees",
        amount: 15000,
        status: "Approved",
        date: "2025-03-10",
        month: "Mar",
      },
    ],
  },
  {
    id: 12,
    department: "Research Department",
    allocated: 70000,
    used: 30000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-034",
        description: "Lab equipment rental",
        amount: 10000,
        status: "Approved",
        date: "2025-01-13",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-035",
        description: "Materials for experiment",
        amount: 10000,
        status: "Approved",
        date: "2025-02-12",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-036",
        description: "Journal subscription",
        amount: 10000,
        status: "Pending",
        date: "2025-03-19",
        month: "Mar",
      },
    ],
  },
  {
    id: 13,
    department: "Security Department",
    allocated: 40000,
    used: 25000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-037",
        description: "Security gear",
        amount: 10000,
        status: "Approved",
        date: "2025-01-15",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-038",
        description: "CCTV maintenance",
        amount: 7000,
        status: "Approved",
        date: "2025-02-22",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-039",
        description: "Uniform replacements",
        amount: 8000,
        status: "Pending",
        date: "2025-03-17",
        month: "Mar",
      },
    ],
  },
  {
    id: 14,
    department: "Customer Support",
    allocated: 65000,
    used: 35000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-040",
        description: "Headset purchases",
        amount: 15000,
        status: "Approved",
        date: "2025-01-18",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-041",
        description: "CRM subscription",
        amount: 10000,
        status: "Pending",
        date: "2025-02-25",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-042",
        description: "Call center overtime meals",
        amount: 10000,
        status: "Approved",
        date: "2025-03-21",
        month: "Mar",
      },
    ],
  },
  {
    id: 15,
    department: "Executive Office",
    allocated: 150000,
    used: 120000,
    transactions: [
      {
        type: "Cash Request",
        referenceId: "CR-043",
        description: "Executive travel fund",
        amount: 50000,
        status: "Approved",
        date: "2025-01-01",
        month: "Jan",
      },
      {
        type: "Liquidation",
        referenceId: "LQ-044",
        description: "Board meeting expenses",
        amount: 40000,
        status: "Approved",
        date: "2025-02-01",
        month: "Feb",
      },
      {
        type: "Reimbursement",
        referenceId: "RB-045",
        description: "Policy review consultancy",
        amount: 30000,
        status: "Approved",
        date: "2025-03-01",
        month: "Mar",
      },
    ],
  },
];
